// Code generated by MockGen. DO NOT EDIT.
// Source: internal/clients/mm/client.go

// Package mock_mm is a generated GoMock package.
package mock_mm

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AddUserToChannels mocks base method.
func (m *MockClient) AddUserToChannels(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToChannels", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToChannels indicates an expected call of AddUserToChannels.
func (mr *MockClientMockRecorder) AddUserToChannels(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToChannels", reflect.TypeOf((*MockClient)(nil).AddUserToChannels), ctx, email)
}

// InviteToTeam mocks base method.
func (m *MockClient) InviteToTeam(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InviteToTeam", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// InviteToTeam indicates an expected call of InviteToTeam.
func (mr *MockClientMockRecorder) InviteToTeam(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteToTeam", reflect.TypeOf((*MockClient)(nil).InviteToTeam), ctx, email)
}
