// Code generated by MockGen. DO NOT EDIT.
// Source: internal/clients/mm/client.go

// Package mock_mm is a generated GoMock package.
package mock_mm

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/mattermost/mattermost/server/public/model"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AddUserToChannels mocks base method.
func (m *MockClient) AddUserToChannels(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToChannels", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToChannels indicates an expected call of AddUserToChannels.
func (mr *MockClientMockRecorder) AddUserToChannels(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToChannels", reflect.TypeOf((*MockClient)(nil).AddUserToChannels), ctx, email)
}

// InviteToTeam mocks base method.
func (m *MockClient) InviteToTeam(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InviteToTeam", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// InviteToTeam indicates an expected call of InviteToTeam.
func (mr *MockClientMockRecorder) InviteToTeam(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteToTeam", reflect.TypeOf((*MockClient)(nil).InviteToTeam), ctx, email)
}

// Mockhttp is a mock of http interface.
type Mockhttp struct {
	ctrl     *gomock.Controller
	recorder *MockhttpMockRecorder
}

// MockhttpMockRecorder is the mock recorder for Mockhttp.
type MockhttpMockRecorder struct {
	mock *Mockhttp
}

// NewMockhttp creates a new mock instance.
func NewMockhttp(ctrl *gomock.Controller) *Mockhttp {
	mock := &Mockhttp{ctrl: ctrl}
	mock.recorder = &MockhttpMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockhttp) EXPECT() *MockhttpMockRecorder {
	return m.recorder
}

// AddChannelMember mocks base method.
func (m *Mockhttp) AddChannelMember(ctx context.Context, channelId, userId string) (*model.ChannelMember, *model.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChannelMember", ctx, channelId, userId)
	ret0, _ := ret[0].(*model.ChannelMember)
	ret1, _ := ret[1].(*model.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddChannelMember indicates an expected call of AddChannelMember.
func (mr *MockhttpMockRecorder) AddChannelMember(ctx, channelId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChannelMember", reflect.TypeOf((*Mockhttp)(nil).AddChannelMember), ctx, channelId, userId)
}

// GetPublicChannelsForTeam mocks base method.
func (m *Mockhttp) GetPublicChannelsForTeam(ctx context.Context, teamId string, page, perPage int, etag string) ([]*model.Channel, *model.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicChannelsForTeam", ctx, teamId, page, perPage, etag)
	ret0, _ := ret[0].([]*model.Channel)
	ret1, _ := ret[1].(*model.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPublicChannelsForTeam indicates an expected call of GetPublicChannelsForTeam.
func (mr *MockhttpMockRecorder) GetPublicChannelsForTeam(ctx, teamId, page, perPage, etag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicChannelsForTeam", reflect.TypeOf((*Mockhttp)(nil).GetPublicChannelsForTeam), ctx, teamId, page, perPage, etag)
}

// GetUserByEmail mocks base method.
func (m *Mockhttp) GetUserByEmail(ctx context.Context, email, etag string) (*model.User, *model.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email, etag)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(*model.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockhttpMockRecorder) GetUserByEmail(ctx, email, etag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*Mockhttp)(nil).GetUserByEmail), ctx, email, etag)
}

// InviteUsersToTeam mocks base method.
func (m *Mockhttp) InviteUsersToTeam(ctx context.Context, teamId string, userEmails []string) (*model.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InviteUsersToTeam", ctx, teamId, userEmails)
	ret0, _ := ret[0].(*model.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InviteUsersToTeam indicates an expected call of InviteUsersToTeam.
func (mr *MockhttpMockRecorder) InviteUsersToTeam(ctx, teamId, userEmails interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteUsersToTeam", reflect.TypeOf((*Mockhttp)(nil).InviteUsersToTeam), ctx, teamId, userEmails)
}
